"use strict";
const LIBRARY = {
  initiative: { key:"initiative", title:"Test samodzielnej inicjatywy", durationDays:4, action:"Przez ustalony czas nie uruchamiaj kontaktu jako pierwszy/pierwsza. Odpowiadaj naturalnie, jeśli druga osoba się odezwie.", dontDo:["Nie ignoruj wiadomości.","Nie opóźniaj odpowiedzi jako kary.","Nie prowokuj ciszy ani konfliktu."], observe:["Czy inicjatywa pojawia się bez Twojego impulsu?","Po jakim czasie i z jaką treścią?","Czy kontakt prowadzi do realnego działania?","Co dzieje się z Twoim napięciem?"], outcomes:["Hipoteza o nierównej inicjatywie została wzmocniona.","Hipoteza została osłabiona przez samodzielny ruch drugiej strony.","Wynik jest niejednoznaczny.","Test był nieważny przez nietypowe okoliczności."] },
  words_actions: { key:"words_actions", title:"Test spójności słów i działań", durationDays:7, action:"Wybierz jedną konkretną deklarację i obserwuj wyłącznie działanie, które miało ją potwierdzić. Nie przypominaj o niej wielokrotnie.", dontDo:["Nie zmieniaj kryterium w trakcie testu.","Nie oceniaj pojedynczego gestu zamiast całego działania.","Nie prowokuj dowodu."], observe:["Czy działanie nastąpiło?","Czy było samodzielne?","Czy utrzymało się poza jednym dniem?","Czy wymagało Twojego prowadzenia?"], outcomes:["Deklaracja znalazła pokrycie.","Pokrycie było częściowe.","Zachowanie nie potwierdziło deklaracji.","Brak wystarczających danych."] },
  repair: { key:"repair", title:"Test odpowiedzialności po konflikcie", durationDays:7, action:"Po kolejnym naturalnym napięciu nie przejmuj automatycznie całego domknięcia. Komunikuj się spokojnie i obserwuj, czy druga strona sama wróci do problemu.", dontDo:["Nie wywołuj konfliktu.","Nie stosuj ciszy jako kary.","Nie odmawiaj bezpiecznej rozmowy."], observe:["Kto wraca do tematu?","Czy pojawia się odpowiedzialność?","Czy zachowanie się zmienia?","Czy wraca tylko spokój bez rozwiązania?"], outcomes:["Odpowiedzialność jest współdzielona.","Naprawa nadal pozostaje głównie po Twojej stronie.","Wynik jest mieszany."] },
  boundary: { key:"boundary", title:"Test respektowania granicy", durationDays:7, action:"Zakres granicy sformułuj jasno, konkretnie i bez groźby. Obserwuj reakcję oraz zachowanie po rozmowie.", dontDo:["Nie używaj granicy jako kary.","Nie stawiaj warunku, którego nie zamierzasz utrzymać.","Nie testuj tego przy ryzyku odwetu."], observe:["Czy granica została zrozumiana?","Czy jest respektowana bez negocjowania jej za każdym razem?","Czy pojawia się odwet, presja lub ośmieszanie?"], outcomes:["Granica jest respektowana.","Granica jest respektowana częściowo.","Granica została przekroczona.","Test należy przerwać ze względów bezpieczeństwa."] },
};
function choose(key, caseModel) {
  const selected = LIBRARY[key] || LIBRARY.initiative;
  return { ...selected, hypothesis: caseModel?.mainHypothesis?.title || "Sprawdzenie głównej hipotezy", reason: caseModel?.recommendedProtocol?.reason || "Ten test zbiera brakujący obserwowalny materiał.", safetyNote:"To nie jest manipulacja ani próba wymuszenia zachowania. Przerwij, jeśli pojawi się zagrożenie, odwet lub silny kryzys." };
}
module.exports = { LIBRARY, choose };
