"use strict";
const express = require("express");
const rateLimit = require("express-rate-limit");
const c = require("../controllers/v3.controller");
const router = express.Router();
const normal = rateLimit({ windowMs:10*60*1000, max:80, standardHeaders:true, legacyHeaders:false, message:{ok:false,error:"Zbyt wiele zapytań. Poczekaj chwilę."} });
const ai = rateLimit({ windowMs:10*60*1000, max:24, standardHeaders:true, legacyHeaders:false, message:{ok:false,error:"Limit analizy został chwilowo osiągnięty."} });
router.post("/session/start", normal, c.start);
router.post("/mirror", ai, c.mirror);
router.post("/interview/next", ai, c.nextQuestion);
router.post("/analyze", ai, c.analyze);
router.post("/boundaries", normal, c.boundaries);
router.post("/protocol/start", normal, c.startProtocol);
router.get("/return/:token", normal, c.recover);
router.post("/checkin/protocol", ai, c.protocolCheckin);
router.post("/checkin/weekly", normal, c.weeklyCheckin);
router.post("/event", normal, c.event);
router.delete("/case", normal, c.remove);
module.exports = router;
